
server:
  port: 8085


spring:
  config:
    import: optional:secrets-dev.yaml

  application:
    name: InstaForms
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  output:
    ansi:
      enabled: always

#  cache:
#    redis:
#      time-to-live: 5000ms
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      timeout: 6000ms
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000


  # RabbitMQ configuration
  rabbitmq:
    host: puffin-01.rmq2.cloudamqp.com
    port: 5671
    username: pxpjftor
    virtual-host: pxpjftor
    ssl:
      enabled: true



#  Mail configurations

logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.data.redis.connection: DEBUG
    org.springframework.data.redis.core: DEBUG
    org.springframework.data.redis.serializer: DEBUG


rabbit:
  email:
    exchange: emailExchange
    routing-key: emailRoutingKey
    queue: emailQueue
  dlx:
    exchange: dlxExchange
    routing-key: dlxRotingKey
    queue: dlxQueue









