spring:
  mail:
    username: aryanrandom20@gmail.com
    password: yvxlvramwiskxysb


  datasource:
    url: jdbc:postgresql://localhost:5432/Instaforms
    username: postgres
    password: qwerty123




email:
  password: yvxlvramwiskxysb
  username: aryanrandom20@gmail.com

